version-0.12.60
sizebay/Sizebay-Catalog-API-Client pull request #305
Opened 2023-07-07 18:19 UTC by Thiago-Gomes626

- added method to call on catalog-api to retrieve tenants by user

2023-07-12 18:02 UTC, heeisenbeergg requested changes

2023-07-12 18:02 UTC, heeisenbeergg commented on src/main/java/sizebay/catalog/client/CatalogAPI.java
> +		return client.getList(ENDPOINT_TENANTS + "/user/" + userId, Tenant.class);
Alterar o endpoint para `users`

2023-08-02 13:56 UTC, joaoschmalz approved these changes

2023-08-02 14:04 UTC, heeisenbeergg approved these changes

2023-08-02 14:09 UTC, merged